### ISSUE TITLE
Multiple references to unknown host: test.ttcloud.net

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-iot-stack#77]
https://fiware-iot-stack.readthedocs.io/en/latest/search.html?q=test.ttcloud.net

**Comment by fgalan** [comment]
https://github.com/telefonicaid/fiware-iot-stack/search?l=Markdown&q=test.ttcloud.net&type=

**Comment by AlvaroVega** [comment]
data_api is using ```<component_host> : <component_port>```
device_api is not using host reference

**Comment by fgalan** [comment]
Fixec by PR https://github.com/telefonicaid/fiware-iot-stack/pull/78
